Adding Ubuntu22 and Oracle Linux 8 in InnoDB CLuster
Percona-QA/package-testing pull request #183
Opened 2022-05-26 06:10 UTC by kaushikpuneet07

2022-06-14 14:04 UTC, kaushikpuneet07 commented
Successful Job after update : https://ps80.cd.percona.com/job/test-ps-innodb-cluster/118/consoleFull

2022-06-16 06:50 UTC, kaushikpuneet07 commented
Removed Centos 6

2022-06-16 07:04 UTC, EvgeniyPatlan requested changes

2022-06-16 07:04 UTC, EvgeniyPatlan commented on molecule/ps-innodb-cluster/Jenkinsfile
> +    choice(name: 'TEST_DIST', choices: ['bento/ubuntu-20.04','bento/ubuntu-18.04','bento/ubuntu-16.04','bento/debian-10','bento/debian-9','bento/centos-8','bento/centos-7','generic/oracle8'], descrip
ubuntu 16.04 is EOL you can remove it

2022-06-16 13:27 UTC, merged