Add OL9 and Ubuntu Jammy in InnoDB Cluster Job
Percona-QA/package-testing pull request #293
Opened 2022-11-12 11:52 UTC by kaushikpuneet07

2022-11-15 18:46 UTC, kaushikpuneet07 commented
Successful Builds after update :

Jammy : https://ps80.cd.percona.com/job/test-ps-innodb-cluster/217/

OL9 : https://ps80.cd.percona.com/job/test-ps-innodb-cluster/216/

2022-11-16 08:39 UTC, eleo007 requested changes

2022-11-16 08:39 UTC, eleo007 commented on molecule/ps-innodb-cluster/Jenkinsfile
> +    choice(name: 'TEST_DIST', choices: ['bento/ubuntu-20.04','bento/ubuntu-18.04','bento/debian-10','bento/centos-7','bento/oracle-8','generic/oracle9','bento/ubuntu-22.04'], description: 'On which i
Lets use bento but not generic image for consistency for oracle9

2022-11-16 10:59 UTC, eleo007 approved these changes

2022-11-16 11:01 UTC, merged