Adding pxc57 molecule components for package-testing
Percona-QA/package-testing pull request #304
Opened 2022-11-22 15:42 UTC by panchal-yash

Add AMIs for pxc57 for ps80 jenkins server

Change instance type to t2.small

Add oracle linux 8 instead of centos 8

Adding python3-mysqldb for ubuntu-bionic, debian-bullseye

adding throttle: 1 for starting and running bats

2022-11-23 10:04 UTC, eleo007 requested changes
PXC 57 tests have 'pxc57_repo' option. PXC57 packages are stored in 2 repos: original and pxc57. So we need to move this functionality here - to select in from what repo to install packages for test.

2022-11-23 10:04 UTC, eleo007 commented on molecule/pxc/pxc57-common/molecule/vagrant/molecule.yml
> +        sleep_before_tests: 40
Indentation - new line.

2022-11-23 10:04 UTC, eleo007 commented on molecule/pxc/pxc57-common/tasks/main.yml
> +    when: (ansible_os_family == "Debian" and ansible_distribution_release != "focal") and (ansible_os_family == "Debian" and ansible_distribution_release != "bionic") and (ansible_os_family == "Debia
The same as for bootstrap

2022-11-23 15:00 UTC, panchal-yash commented on molecule/pxc/pxc57-bootstrap/tasks/main.yml
> +    when: (ansible_os_family == "Debian" and ansible_distribution_release != "focal") and (ansible_os_family == "Debian" and ansible_distribution_release != "bionic") and (ansible_os_family == "Debia
Yes I shortened them using the following condition and tested it.

when: (ansible_os_family == "Debian") and (ansible_distribution_release != "focal" and ansible_distribution_release != "bionic" and ansible_distribution_release != "bullseye")

2022-11-24 13:02 UTC, eleo007 approved these changes

2022-11-25 06:42 UTC, merged