PMM-7 cleanup unused psmdb files
Percona-QA/package-testing pull request #444
Opened 2023-06-01 16:19 UTC by vyarosh

2023-06-02 18:49 UTC, olexandr-havryliak approved these changes

2023-06-05 06:50 UTC, eleo007 requested changes
Hi,
File package-testing/tasks/install_and_run_psmdb.yml and all the corresponding links from it are used for PT tests. Please revert changes related to mentioned file.

2023-12-12 01:19 UTC, vyarosh commented
@eleo007 reverted 3 files used in `pt_with_products.yml` playbook. Please review.

2023-12-12 12:55 UTC, eleo007 approved these changes

2023-12-12 19:36 UTC, merged